# Layout of this file
# <source_type>:
#   image_namespace: <namespace> -- optional
#   image: <image_ref>

---
openshift:
  image: "topological-inventory-openshift:latest"
amazon:
  image: "topological-inventory-amazon:latest"
